import React from "react";
import { ScrollView, Text, StyleSheet } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, spacing, typography } from "@/theme";

export default function TermsScreen() {
  return (
    <SafeAreaView style={styles.container} edges={["bottom"]}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.heading}>Identification is AI-assisted, not a guarantee</Text>
        <Text style={styles.body}>
          Brand, model, reference number, and authenticity notes are
          generated by an AI model from the photos you provide and may be
          inaccurate or incomplete. Always verify reference numbers and
          authenticity through an authorized dealer or qualified watchmaker
          before relying on this app's output for a purchase, sale, or
          insurance decision.
        </Text>

        <Text style={styles.heading}>Valuations are estimates</Text>
        <Text style={styles.body}>
          Market value estimates are derived from active marketplace
          listing prices, not realized sale prices, and do not constitute a
          professional appraisal. Actual sale prices may differ
          significantly.
        </Text>

        <Text style={styles.heading}>Subscriptions</Text>
        <Text style={styles.body}>
          Paid tiers increase your daily scan allowance and portfolio
          history retention as described on the Upgrade screen. Subscriptions,
          once available, are billed and managed through Google Play and can
          be cancelled at any time through your Google Play account settings.
        </Text>

        <Text style={styles.heading}>Account deletion</Text>
        <Text style={styles.body}>
          You may delete your account at any time from Settings. This action
          is permanent and cannot be undone.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, gap: spacing.md },
  heading: { ...typography.heading, color: colors.textPrimary, marginTop: spacing.md },
  body: { ...typography.body, color: colors.textSecondary, lineHeight: 22 },
});
